### PR TITLE
Fixed import another lib syntax

### PR DESCRIPTION
**Pull request by chawatvish**

### CODE REVIEW

**Comment by chawatvish** [comment]
For more detail please check out this link below
https://github.com/adobe/places-monitor-ios/issues/44

**Comment by sbenedicadb** [comment]
Hey @chawatvish - 

Thanks for opening a PR!  We will be reviewing and investigating the changes you've proposed tomorrow.  

If the changes are accepted, we'll need you to [sign the Adobe CLA](https://github.com/adobe/places-monitor-ios/pull/45/checks?check_run_id=305716012) in order for us to merge your PR. 

**steve benedick**
_sr mobile sdk engineer_
adobe experience platform

**Comment by chawatvish** [comment]
Thank you. I will wait for your review.

**Comment by sbenedicadb** [comment]
Hey @chawatvish - 

Changes look good!

If you want to sign the CLA I can merge in this PR.  If you'd rather not sign the CLA, I will open a pull request with these changes.  Thanks again!

-steveb

**Comment by chawatvish** [comment]
Thanks for review. I signed Adobe CLA already.

**Pull request merged**
